# pages.config.yml (or potentially .pages.yml with this structure)
media:
  input: public/images
  output: /images
  extensions: [jpg, jpeg, png, webp, gif]

content:
  # Articles (Blog Posts)
  - name: articles
    label: Articles
    type: collection
    path: src/content/articles # Note: path might differ for your structure
    format: yaml-frontmatter
    filename: "{slug}.md"
    fields:
      - name: title
        type: string
        required: true
      - name: slug
        type: string
        hint: "Used in URL. Lowercase, hyphenated (e.g., my-new-post)"
      - name: date
        type: date
        required: true
      - name: excerpt
        type: text
        hint: "Short summary for listing pages"
      - name: author
        type: string
      - name: cover_image
        type: image
        required: false
        hint: "Featured image for the article"
      - name: tags
        type: list
        field:
          type: string
      - name: body
        type: rich-text # or markdown
        required: true

  # ... other collections like team, services