# .pages.yml - Configuration for Pages CMS
media:
  input: content/images
  output: /content/images
  extensions: [jpg, jpeg, png, webp, gif]

content:
  # Articles Collection
  - name: articles
    label: Articles
    type: collection
    path: content/articles
    format: yaml-frontmatter
    filename: {slug}.md
    fields:
      - name: title
        type: string
        required: true
      - name: slug
        type: string
        required: true
        hint: "Used in filename. Lowercase, hyphenated (e.g., my-first-post)"
      - name: date
        type: date
        required: true
      - name: author
        type: string
      - name: image
        type: image
        required: false
        hint: "Featured image for the article"
      - name: tags
        type: list
        field:
          type: string
      - name: body
        type: markdown
        required: true

  # Team Members Collection
  - name: team
    label: Team Members
    type: collection
    path: content/teams
    format: yaml-frontmatter
    filename: {slug}.md
    fields:
      - name: title
        type: string
        required: true
      - name: slug
        type: string
        required: true
        hint: "Used in filename. Lowercase, hyphenated (e.g., john-doe)"
      - name: role
        type: string
        required: true
      - name: image
        type: image
        required: false
        hint: "Photo of the team member"
      - name: tags
        type: list
        field:
          type: string
      - name: body
        type: markdown
        required: true

  # Services Collection
  - name: services
    label: Services
    type: collection
    path: content/services
    format: yaml-frontmatter
    filename: {slug}.md
    fields:
      - name: title
        type: string
        required: true
      - name: slug
        type: string
        required: true
        hint: "Used in filename. Lowercase, hyphenated (e.g., web-development)"
      - name: image
        type: image
        required: false
        hint: "Icon or image representing the service"
      - name: body
        type: markdown
        required: true