collections:
  - name: articles
    label: Articles
    path: content/articles
    fields:
      - name: title
        label: Title
        type: string
      - name: image
        label: Image
        type: image
      - name: date
        label: Date
        type: datetime
      - name: tags
        label: Tags
        type: list
      - name: author
        label: Author
        type: string
      - name: body
        label: Body
        type: rich-text

  - name: teams
    label: Team Members
    path: content/teams
    fields:
      - name: title
        label: Name
        type: string
      - name: image
        label: Photo
        type: image
      - name: role
        label: Role
        type: string
      - name: tags
        label: Tags
        type: list
      - name: body
        label: Bio
        type: rich-text

  - name: services
    label: Services
    path: content/services
    fields:
      - name: title
        label: Service Name
        type: string
      - name: image
        label: Icon
        type: image
      - name: body
        label: Description
        type: rich-text

media:
  output: content/images
  public: /content/images