collections:
  - name: articles
    label: Articles
    path: content/articles
    extension: md
    fields:
      - name: title
        label: Title
        type: string
      - name: body
        label: Body
        type: rich-text

  - name: teams
    label: Team Members
    path: content/teams
    extension: md
    fields:
      - name: title
        label: Name
        type: string
      - name: body
        label: Bio
        type: rich-text

  - name: services
    label: Services
    path: content/services
    extension: md
    fields:
      - name: title
        label: Service Name
        type: string
      - name: body
        label: Description
        type: rich-text